inherit_from: .rubocop_todo.yml

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
  Exclude:
    - 'frontend/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/apis/api/v1/**/*'
    - 'spec/apis/api/v1/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/apis/api/v1/**/*'
    - 'spec/apis/api/v1/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/apis/api/v1/**/*'
    - 'spec/apis/api/v1/**/*'

Naming/FileName:
  Exclude:
    - 'spec/support/rspec-json_expectations.rb'

Lint/UselessAssignment:
  Exclude:
    - 'app/apis/api/v1/**/*'

Layout/IndentationConsistency:
  Exclude:
    - 'app/apis/api/v1/**/*'

Metrics/BlockLength:
  Enabled: false
